# Generated by Django 3.2.4 on 2021-07-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_touch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touch',
            name='lead',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
