# Generated by Django 3.2.4 on 2021-08-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
