# Generated by Django 3.2.4 on 2021-08-07 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_project_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image1',
        ),
    ]
